name: Continuous Integration

on: [push, pull_request]

jobs:
  PHP_72:
    name: PHP 7.2 Continuous Integration
    runs-on: ubuntu-18.04
    container: 
      image: php:7.2-fpm
      volumes:
        - /app
    steps:
      - name: Run CI
        uses: ./.github/actions/continuous-integration

#  PHP_73:
#    name: PHP 7.3 Continuous Integration
#    runs-on: ubuntu-18.04
#    container:
#      image: php:7.3-fpm
#    steps:
#
#      - name: Validate composer file
#        uses: ./.github/actions/composer-validate
#
#      - name: Install dependencies
#        uses: ./.github/actions/composer-install
#
#      - name: Run tests
#        run: |
#          make coverage-test
