build-template: &build-template
  steps:
    - name: Validate composer file
      run: |
        composer validate

    - name: Install dependencies
      run: |
        make vendor

    - name: Run tests
      run: |
        make coverage-test


name: Continuous Integration

on: [push, pull_request]

jobs:
  PHP_7.2:
    name: PHP 7.2 Continuous Integration
    runs-on: ubuntu-18.04
    container: 
      image: php:7.2-fpm
    <<: *build-template
  PHP_7.3:
    name: PHP 7.3 Continuous Integration
    runs-on: ubuntu-18.04
    container:
      image: php:7.3-fpm
    <<: *build-template

